

package Vistas;


import com.mycompany.pruebaproyecto.ArbolBinario;
import com.mycompany.pruebaproyecto.LeerArchivo;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author david
 */
public class CargarArchivo extends javax.swing.JFrame {
     private ArbolBinario arbolito; 
    /**
     * Creates new form CargarArchivo
     */
    public CargarArchivo() {
        initComponents();
        arbolito = new ArbolBinario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cargarArchivo = new javax.swing.JButton();
        btInorden = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea1 = new javax.swing.JTextArea();
        btpreOrden = new javax.swing.JButton();
        btposOrden = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaDatos = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cargarArchivo.setBackground(new java.awt.Color(51, 153, 255));
        cargarArchivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cargarArchivo.setForeground(new java.awt.Color(255, 255, 255));
        cargarArchivo.setText("Seleccionar Archivo ...");
        cargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarArchivoActionPerformed(evt);
            }
        });

        btInorden.setBackground(new java.awt.Color(51, 153, 255));
        btInorden.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btInorden.setForeground(new java.awt.Color(255, 255, 255));
        btInorden.setText("InOrden");
        btInorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInordenActionPerformed(evt);
            }
        });

        txtArea1.setBackground(new java.awt.Color(204, 204, 204));
        txtArea1.setColumns(20);
        txtArea1.setRows(5);
        jScrollPane1.setViewportView(txtArea1);

        btpreOrden.setBackground(new java.awt.Color(51, 153, 255));
        btpreOrden.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btpreOrden.setForeground(new java.awt.Color(255, 255, 255));
        btpreOrden.setText("PreOrden");
        btpreOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpreOrdenActionPerformed(evt);
            }
        });

        btposOrden.setBackground(new java.awt.Color(51, 153, 255));
        btposOrden.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btposOrden.setForeground(new java.awt.Color(255, 255, 255));
        btposOrden.setText("PosOrden");
        btposOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btposOrdenActionPerformed(evt);
            }
        });

        areaDatos.setBackground(new java.awt.Color(204, 204, 204));
        areaDatos.setColumns(20);
        areaDatos.setRows(5);
        jScrollPane2.setViewportView(areaDatos);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Datos del Archivo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(cargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btInorden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btpreOrden)
                        .addGap(18, 18, 18)
                        .addComponent(btposOrden))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btInorden)
                            .addComponent(btpreOrden)
                            .addComponent(btposOrden))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(cargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarArchivoActionPerformed
        LeerArchivo arch = new LeerArchivo();
        JFileChooser fileChooser = new JFileChooser();
        int rps = fileChooser.showOpenDialog(null);   
        
        File fich = fileChooser.getSelectedFile();
        
        arch.leerArch(arbolito, fich, areaDatos);
    }//GEN-LAST:event_cargarArchivoActionPerformed

    private void btInordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInordenActionPerformed
        StringBuilder dat = new StringBuilder();
        txtArea1.setText("");
        if(arbolito != null && !arbolito.EstaVacio()){
        arbolito.InOrden(arbolito.raiz, dat);
        }
        txtArea1.setText(dat.toString());
    }//GEN-LAST:event_btInordenActionPerformed

    private void btpreOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpreOrdenActionPerformed
        StringBuilder dat = new StringBuilder();
        txtArea1.setText("");
        if (arbolito != null && !arbolito.EstaVacio()) {
        arbolito.PreOrden(arbolito.raiz, dat);
        }
        txtArea1.setText(dat.toString());
    }//GEN-LAST:event_btpreOrdenActionPerformed

    private void btposOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btposOrdenActionPerformed
        StringBuilder dat = new StringBuilder();
        txtArea1.setText("");
        if (arbolito != null && !arbolito.EstaVacio()) {
        arbolito.PostOrden(arbolito.raiz, dat);
        }
        txtArea1.setText(dat.toString());
    }//GEN-LAST:event_btposOrdenActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDatos;
    private javax.swing.JButton btInorden;
    private javax.swing.JButton btposOrden;
    private javax.swing.JButton btpreOrden;
    private javax.swing.JButton cargarArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtArea1;
    // End of variables declaration//GEN-END:variables
}
